# Generated by Django 5.0.4 on 2025-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emission_type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
            ],
        ),
    ]
